// Writes src/generated/operations.gen.ts from openapi.json: the method and
// path of every operation an API key can call, and its hey-api request and
// response types. Session-only operations (organizations, projects, members,
// API keys, billing) belong to the web app and are left out.
import { readFileSync, writeFileSync } from "node:fs"

interface Operation {
  operationId: string
  security?: Record<string, string[]>[]
}

interface Spec {
  security: Record<string, string[]>[]
  paths: Record<string, Record<string, Operation>>
  components: { schemas: Record<string, unknown> }
}

const METHODS = ["get", "post", "put", "patch", "delete"] as const
const spec = JSON.parse(readFileSync("openapi.json", "utf8")) as Spec

const pascal = (id: string) =>
  id.replace(/(^|_)([a-z])/g, (_, __, letter: string) => letter.toUpperCase())

const callableWithApiKey = (operation: Operation) => {
  const security: Record<string, string[]>[] =
    operation.security ?? spec.security
  return security.length === 0 || security.some((s) => "apiKey" in s)
}

const operations: { id: string; method: string; path: string }[] = []
for (const [path, item] of Object.entries(spec.paths)) {
  for (const method of METHODS) {
    const operation = item[method]
    if (operation && callableWithApiKey(operation)) {
      operations.push({
        id: operation.operationId,
        method: method.toUpperCase(),
        path,
      })
    }
  }
}
operations.sort((a, b) => a.id.localeCompare(b.id))

const source = `// Generated by scripts/operations.ts from openapi.json. Do not edit.
import type * as T from "./types.gen.ts"

export const OPERATIONS = {
${operations.map((o) => `  ${o.id}: { method: "${o.method}", path: "${o.path}" },`).join("\n")}
} as const

export type OperationId = keyof typeof OPERATIONS

export interface Operations {
${operations.map((o) => `  ${o.id}: { data: T.${pascal(o.id)}Data; response: T.${pascal(o.id)}Response }`).join("\n")}
}
`
writeFileSync("src/generated/operations.gen.ts", source)

// The schemas, as the SDK exports them. `Record` is left out: exported at the
// top level it would shadow TypeScript's `Record<K, V>` (it is `NoheadRecord`).
const schemas = Object.keys(spec.components.schemas)
  .filter((name) => name !== "Record")
  .sort()
writeFileSync(
  "src/generated/schemas.gen.ts",
  `// Generated by scripts/operations.ts from openapi.json. Do not edit.
export type {
${schemas.map((name) => `  ${name},`).join("\n")}
} from "./types.gen.ts"
`
)
console.log(`${operations.length} operations, ${schemas.length} schemas`)
